package findTheDifference

/*
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

// func findTheDifference(s string, t string) byte {
// 	m := make([]int, 26)
// 	for i := 0; i < len(s); i++ {
// 		m[s[i]-'a']++
// 		m[t[i]-'a']++
// 	}
// 	m[t[len(t)-1]-'a']++
// 	for idx, count := range m {
// 		if count%2 != 0 {
// 			return byte(idx) + 'a'
// 		}
// 	}
// 	return byte(0)
// }

// func findTheDifference(s string, t string) byte {
// 	sb := []byte(s)
// 	tb := []byte(t)
// 	sSum := 0
// 	tSum := int(tb[len(tb)-1])
// 	for i := 0; i < len(sb); i++ {
// 		sSum += int(sb[i])
// 		tSum += int(tb[i])
// 	}
// 	return byte(tSum - sSum)
// }

// Runtime: 0 ms, faster than 100.00% of Go online submissions for Find the Difference.
// Memory Usage: 2.2 MB, less than 55.06% of Go online submissions for Find the Difference.

func findTheDifference(s string, t string) byte {
	var i int
	result1, result2 := uint8(0), uint8(0)
	for i = 0; i < len(s); i++ {
		result1 ^= s[i]
		result2 ^= t[i]
	}
	result2 ^= t[i]
	return result1 ^ result2
}
